export enum TransactionType {
    Sale = 'Sale',
    Auth = 'Auth',
    Vft = 'Vft',
    Point = 'Point',
    Cancel = 'Cancel',
    Refund = 'Refund',
    Capture = 'Capture',
    Reversal = 'Reversal',
    CampaignSearch = 'CampaignSearch',
    CardTest = 'CardTest',
    BatchClosedSuccessSearch = 'BatchClosedSuccessSearch',
    SurchargeSearch = 'SurchargeSearch',
    VFTSale = 'VFTSale',
    VFTSearch = 'VFTSearch',
    PointSearch = 'PointSearch',
    PointSale = 'PointSale',
    Credit = 'Credit',
}